[package]
name = "binserve"
version = "0.1.0"
authors = ["mufeedvh <mufeedvh@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
env_logger = "0.8.4"

actix-web = "3"
actix-files = "0.5.0"

clap = "2.33.3"

[profile.release]
lto = true